import { gs100, kt6300, kt6610, qc_kt6610, uri100 } from "@/results";

export const patient_data = [
  {
    in_visit: true,
    patient_id: "AMA-00001",
    name: "Belle Beverly Olson",
    gender: "Male",
    age: "36 YRS",
    mobile: "+255 676 021 226",
    date_added: "13-MAR-2024 11:00",
    address: "Temeke, Dar es Salaam",
    origin: "AMA",
    last_visit: "13-MAR-2024 11:00",
  },
  {
    in_visit: true,
    patient_id: "AMA-00002",
    name: "Denizer Frank Peter",
    gender: "Female",
    age: "24 YRS",
    mobile: "+255 429 825 003",
    address: "Ilala, Dar es Salaam",
    date_added: "12-MAR-2024 11:00",
    origin: "AMA",
    last_visit: "12-MAR-2024 11:00",
  },
  {
    in_visit: false,
    patient_id: "AMA-00003",
    name: "Jackson Jonas Jonathan",
    gender: "Male",
    age: "32 YRS",
    mobile: "+255 767 121 878",
    address: "Kibaha, Pwani",
    date_added: "10-MAR-2024 11:00",
    origin: "EMedical",
    last_visit: "10-MAR-2024 11:00",
  },
];

export const visit_data = [
  {
    reference: "SA3434343",
    date: "12-MAR-2023 11:00",
    checkin_as: "Inpatient",
    department: "Haematology",
    location: "OPD Ward 3",
    status: "IN VISIT",
  },
  {
    reference: "SA3434343",
    date: "12-MAR-2023 11:00",
    checkin_as: "Inpatient",
    department: "Haematology",
    location: "OPD Ward 3",
    status: "IN VISIT",
  },
];

export const vitals = [
  {
    date: "12-MAR-2023 11:00",
    temp: "38",
    blood_pressure: "128 / 78",
    pulse: "20",
    r_rate: "16",
    spo: "97",
    weight: "56",
    height: "150",
    bmi: "24.9",
  },
  {
    date: "13-MAR-2023 11:00",
    temp: "38",
    blood_pressure: "128 / 78",
    pulse: "20",
    r_rate: "16",
    spo: "97",
    weight: "56",
    height: "150",
    bmi: "24.9",
  },
];

export const test_data = [
  {
    id: 1,
    accession_no: "ASA434989",
    requested_by: "Dr. Bilal Umar",
    priority: "Urgent",
    total_tests: "3",
    progress: "90%",
    date_created: "12-MAR-2023 11:00",
    status: "Pending",
  },
  {
    id: 1,
    accession_no: "ASA434989",
    requested_by: "Dr. Bilal Umar",
    priority: "Urgent",
    total_tests: "3",
    progress: "90%",
    date_created: "12-MAR-2023 11:00",
    status: "Pending",
  },
  {
    id: 1,
    accession_no: "ASA434989",
    requested_by: "Dr. Bilal Umar",
    priority: "Urgent",
    total_tests: "3",
    progress: "90%",
    date_created: "12-MAR-2023 11:00",
    status: "Pending",
  },
];

export const checkin_data = [
  {
    id: 1,
    visit_no: "ID1000001",
    patient_id: "AMA-00002",
    name: "Denizer Frank Peter",
    gender: "Female",
    age: "24 YRS",
    mobile: "+255 429 825 003",
    address: "Ilala, Dar es Salaam",
    date_added: "12-MAR-2024 11:00",
    origin: "AMA",
    last_visit: "12-MAR-2024 11:00",
    visit_time: "24-Feb-2024, 10:22 AM",
    reference: "1000D2E",
    department: "Haematology",
    section: "Haematology DP01",
    checkin_type: "Inpatient",
    status: "In Visit",
  },
  {
    in_visit: false,
    visit_no: "ID1000001",
    patient_id: "AMA-00003",
    name: "Jackson Jonas Jonathan",
    gender: "Male",
    age: "32 YRS",
    mobile: "+255 767 121 878",
    address: "Kibaha, Pwani",
    date_added: "10-MAR-2024 11:00",
    origin: "EMedical",
    last_visit: "10-MAR-2024 11:00",
    visit_time: "24-Feb-2024, 10:22 AM",
    reference: "1000D2E",
    department: "Haematology",
    section: "Haematology DP01",
    checkin_type: "Inpatient",
    status: "In Visit",
  },
];

export const clinical_notes = [
  {
    id: 1,
  },
  {
    id: 2,
  },
  {
    id: 3,
  },
  {
    id: 4,
  },
];

export const diseases = [
  { label: "Cholera", value: "Cholera" },
  { label: "Botulism", value: "Botulism" },
  { label: "Amoebiasis", value: "Amoebiasis" },
  { label: "Balantidiasis", value: "Balantidiasis" },
  { label: "Isosporiasis", value: "Isosporiasis" },
  { label: "Giardiasis", value: "Giardiasis" },
  { label: "Rotaviral", value: "Rotaviral" },
  { label: "Adenoviral", value: "Adenoviral" },
  {
    label: "Tuberculosis of lung",
    value: "Tuberculosis of lung",
    disable: false,
  },
  {
    label: "Miliary tuberculosis",
    value: "Miliary tuberculosis",
    disable: false,
  },
  {
    label: "Acute miliary tuberculosis of a single specified site",
    value: "acute",
  },
];

export const qc_samples = [
  { label: "DH2307N-01", value: "DH2307N-01" },
  { label: "DH2307N-02", value: "DH2307N-02" },
  { label: "DH2307N-03", value: "DH2307N-03" },
  { label: "DJ2408B-01", value: "DJ2408B-01" },
  { label: "DJ2408B-02", value: "DJ2408B-02" },
  { label: "DJ2408B-03", value: "DJ2408B-03" },
];

export const medical_diagnosis = [
  {
    id: 1,
  },
  {
    id: 2,
  },
  {
    id: 3,
  },
  {
    id: 4,
  },
];

export const laborarory_requests = [
  {
    date: "24-Feb-2024, 10:22 AM",
    req_number: "ORDER-0001",
    accession_number: "20231212-1611",
    total_tests: "2 Tests",
    status: "New",
    origin: "AMA",
    requested_by: "Dr. Kelvin Straus",
    urgency: "Routine",
    order_type: "Test Order",
  },
  {
    date: "24-Mar-2024, 12:22 PM",
    req_number: "ORDER-0002",
    accession_number: "20231212-1621",
    total_tests: "2 Tests",
    status: "New",
    origin: "AMA",
    requested_by: "Dr. Kelvin Straus",
    urgency: "Routine",
    order_type: "Test Order",
  },
];

export const vitals_data = [
  {
    name: "Blood Pressure",
    short_name: "BP",
    unit: "mmHg",
    value: "80 / 90",
    abnormality: true,
    abnormal_value: "low",
  },
  {
    name: "Heart Rate",
    short_name: "H.Rate",
    unit: "beats/min",
    value: "79",
    abnormality: false,
    abnormal_value: null,
  },
  {
    name: "Respiratory Rate",
    short_name: "R.Rate",
    unit: "breaths/min",
    value: "7",
    abnormality: true,
    abnormal_value: "high",
  },
  {
    name: "Oxygen Saturation SpO2",
    short_name: "SpO2",
    unit: "%",
    value: "97",
    abnormality: false,
    abnormal_value: null,
  },
  {
    name: "Body Temperature",
    short_name: "Temp",
    unit: "°C",
    value: "37.1",
    abnormality: false,
    abnormal_value: null,
  },
  {
    name: "Weight",
    short_name: "Weight",
    unit: "KG",
    value: "69",
    abnormality: false,
    abnormal_value: null,
  },
  {
    name: "Height",
    short_name: "Height",
    unit: "CM",
    value: "165",
    abnormality: false,
    abnormal_value: null,
  },
  {
    name: "BMI",
    short_name: "BMI",
    unit: "KG / M²",
    value: "165",
    abnormality: false,
    abnormal_value: null,
  },
];

export const test_types = [
  {
    id: 1,
    name: "24 Hour Urine Collection",
    short_name: "Urine Col",
    number: "780081",
  },
  { id: 2, name: "Adenosine", short_name: "ADA", number: "780082" },
  { id: 3, name: "Blood Group Rhesus", short_name: "", number: "780083" },
  { id: 4, name: "C4 Complement", short_name: "", number: "780084" },
  { id: 5, name: "Cadmium", short_name: "", number: "780085" },
  { id: 6, name: "Cholesterol", short_name: "", number: "780086" },
  { id: 7, name: "Chord Blood", short_name: "", number: "780087" },
  { id: 8, name: "Cigna", short_name: "", number: "780088" },
  { id: 9, name: "CSF Culture", short_name: "", number: "780089" },
  { id: 10, name: "CSF Routine / Biochem", short_name: "", number: "78010" },
];

export const test_panels = [
  {
    id: 1,
    name: "Lipid Profile Panel",
    short_name: "LPP Panel",
    number: "800881",
  },
  {
    id: 2,
    name: "Basic Metabolic Panel",
    short_name: "BMP Panel",
    number: "800892",
  },
  {
    id: 3,
    name: "Electrolyte Panel",
    short_name: "ELEC Panel",
    number: "800853",
  },
  {
    id: 4,
    name: "Liver / Hepatic Function Panel",
    short_name: "HLF Panel",
    number: "800172",
  },
  {
    id: 5,
    name: "Renal / Kidney Function Panel",
    short_name: "KRF Panel",
    number: "800310",
  },
  {
    id: 6,
    name: "Thyroid Function Panel",
    short_name: "TF Panel",
    number: "800506",
  },
];

export const lab_tests = [
  {
    id: 1,
    name: "Full Blood Picture",
    date: "24-Feb-2024, 10:22 AM",
    specimen: "Whole Blood",
    collected: "24-Feb-2024, 10:22 AM",
    collected_by: "User",
    condition: "Acceptable",
    status: "Pending",
    results: kt6610.observation_results,
  },
  {
    id: 1,
    name: "Urinalysis",
    date: "25-Feb-2024, 12:03 AM",
    specimen: "Serum",
    collected: "24-Feb-2024, 10:22 AM",
    collected_by: "User",
    condition: "Acceptable",
    status: "Pending",
    results: uri100.observation_results,
  },
];

export const lab_results = [
  {
    id: 1,
    name: "Full Blood Picture",
    visit: "ED333210",
    date: "24-MAR-2024, 12:22 PM",
    requested_by: "Dr. Nia Bamgomshe",
    result_date: "24-Feb-2024, 13:50 PM",
    status: "Verified",
    specimen_details: {
      name: "Whole Blood",
      collected: "Super User",
      collection_date: "24-Feb-2024, 12:03 PM",
      condition: "Acceptable",
    },
    results: qc_kt6610.observation_results,
  },
  {
    id: 2,
    name: "Urinalysis",
    visit: "ED335711",
    date: "24-Feb-2024, 10:22 AM",
    requested_by: "Dr. Nia Bamgomshe",
    result_date: "24-Feb-2024, 13:50 PM",
    status: "Verified",
    specimen_details: {
      name: "Serum",
      collected: "Super User",
      collection_date: "24-Feb-2024, 12:03 PM",
      condition: "Acceptable",
    },
    results: uri100.observation_results,
  },
  {
    id: 2,
    name: "Cholesterol",
    visit: "ED333210",
    date: "24-Feb-2024, 10:22 AM",
    requested_by: "Dr. Ali Saleh",
    result_date: "24-Feb-2024, 13:50 PM",
    status: "Verified",
    specimen_details: {
      name: "Serum",
      collected: "Super User",
      collection_date: "24-Feb-2024, 12:03 PM",
      condition: "Acceptable",
    },
    results: [],
  },
];

export const lab_orders = [
  {
    id: 1,
    date: "24-Feb-2024, 12:03 PM",
    origin: "AMA",
    request_no: "ORDER-0011",
    total_tests: "2",
    completed: "0",
    insurance: "nhif",
    accession_no: "20231212-1621",
    patient_id: "PR63848",
    patient_name: "Jacqueline Peter Lyimo",
    age_gender: "27, Female",
    status: "New",
    requested_by: "Dr. Super User",
    priority: "Emergency",
  },
  {
    id: 2,
    date: "24-Feb-2024, 12:03 PM",
    origin: "AMA",
    request_no: "ORDER-0013",
    total_tests: "2 ",
    completed: "2",
    insurance: "assemble",
    accession_no: "20231212-1631",
    patient_id: "PR63848",
    patient_name: "Jacqueline Peter Lyimo",
    age_gender: "27, Female",
    status: "Complete",
    requested_by: "Dr. Super User",
    priority: "Urgent",
  },
  {
    id: 3,
    date: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_no: "ORDER-0025",
    total_tests: "2",
    completed: "1",
    insurance: "nhif",
    accession_no: "20231212-1645",
    patient_id: "PR63326",
    patient_name: "Alice Jackson John",
    age_gender: "24, Female",
    status: "Pending",
    requested_by: "Dr. Super User",
    priority: "Routine",
  },
  {
    id: 3,
    date: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_no: "ORDER-0025",
    total_tests: "2",
    completed: "1",
    insurance: "nhif",
    accession_no: "20231212-1645",
    patient_id: "PR63326",
    patient_name: "Alice Jackson John",
    age_gender: "24, Female",
    status: "Incomplete",
    requested_by: "Dr. Super User",
    priority: "Routine",
  },
];

export const specimen_data = [
  {
    id: 1,
    name: "Seminal Fluid",
    number: "IS0910",
  },
  {
    id: 2,
    name: "CSF",
    number: "IS0921",
  },
  {
    id: 3,
    name: "Blood",
    number: "IS0911",
  },
  {
    id: 2,
    name: "Urine",
    number: "IS0913",
  },
  {
    id: 2,
    name: "Stool",
    number: "IS0919",
  },
];

export const users_list = [
  {
    id: 1,
    name: "Jonas Jonathan",
    number: "AMA-0001",
    designation: "Manager",
    role: "Lab Manager",
    email: "jonas@gmail.com",
    phone: "0788990009",
    last_online: "21-MAR-2024, 12:00 PM",
    status: "Active",
  },
  {
    id: 2,
    name: "Peter Michael",
    number: "AMA-0002",
    designation: "Technician",
    role: "Lab Technician",
    email: "petermichael@gmail.com",
    phone: "0788990009",
    last_online: "23-MAR-2024, 12:00 PM",
    status: "Active",
  },
  {
    id: 3,
    name: "Salim Salum",
    number: "AMA-0003",
    designation: "Doctor",
    role: "Doctor",
    email: "salims@gmail.com",
    phone: "0788990009",
    last_online: "20-MAR-2024, 12:00 PM",
    status: "Active",
  },
  {
    id: 4,
    name: "Alice Masu",
    number: "AMA-0004",
    designation: "Technician",
    role: "Lab Technician",
    email: "alice@live.com",
    phone: "0788990009",
    last_online: "21-MAR-2024, 12:00 PM",
    status: "Active",
  },
  {
    id: 5,
    name: "Super User",
    number: "AMA-0005",
    designation: "Developer",
    role: "Developer",
    email: "superuser@hotmail.com",
    phone: "0788990009",
    last_online: "25-MAR-2024, 12:00 PM",
    status: "Active",
  },
];

export const rejections = [
  { id: 1, name: "Insufficient Quantity", iso_code: "" },
  { id: 2, name: "Improper Labeling", iso_code: "" },
  { id: 3, name: "Clotted Specimen", iso_code: "" },
  { id: 4, name: "Hemolyzed Specimen", iso_code: "" },
  { id: 5, name: "Contamination", iso_code: "" },
  { id: 6, name: "Expired Specimen", iso_code: "" },
  { id: 7, name: "Incorrect Specimen Type", iso_code: "" },
  { id: 8, name: "Transportation Issues", iso_code: "" },
  { id: 9, name: "Specimen Leakage", iso_code: "" },
  { id: 10, name: "Inappropriate Handling", iso_code: "" },
];

export const specimen_list = [
  {
    id: 1,
    datetime: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_number: "ORDER-0011",
    sample_number: "202403000020-01D",
    sample_name: "Whole Blood",
    shipped: "no",
    test_name: "Cholesterol",
    collected_by: "Super User",
    patient_id: "P12242",
    patient_name: "Alice John",
    age_gender: "24, Female",
    status: "Pending",
    sample_color: "text-green-400",
    isRecollected: "Yes",
  },
  {
    id: 2,
    datetime: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_number: "ORDER-0012",
    sample_number: "202403000020-01D",
    sample_name: "Whole Blood",
    shipped: "no",
    test_name: "Cholesterol",
    collected_by: "Super User",
    patient_id: "P12242",
    patient_name: "Alice John",
    age_gender: "24, Female",
    status: "Rejected",
    sample_color: "text-green-400",
    isRecollected: "No",
  },
  {
    id: 3,
    datetime: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_number: "ORDER-0013",
    sample_number: "202403000020-01D",
    sample_name: "Whole Blood",
    shipped: "no",
    test_name: "Cholesterol",
    collected_by: "Super User",
    patient_id: "P12242",
    patient_name: "Alice John",
    age_gender: "24, Female",
    status: "Collected",
    sample_color: "text-green-400",
    isRecollected: "Yes",
  },
  {
    id: 3,
    datetime: "24-Feb-2024, 11:20 PM",
    origin: "AMA",
    request_number: "ORDER-0013",
    sample_number: "202403000020-01D",
    sample_name: "Whole Blood",
    shipped: "no",
    test_name: "Cholesterol",
    collected_by: "Super User",
    patient_id: "P12242",
    patient_name: "Alice John",
    age_gender: "24, Female",
    status: "Received",
    sample_color: "text-green-400",
    isRecollected: "No",
  },
];

export const results_data = [
  {
    release_date: "24-Feb-2024, 11:20 PM",
    sample_number: "202403000020-01D",
    test_name: "Full Blood Picture",
    result_number: "RES-001",
    process_method: "Machine",
    source: "AMA",
    patient_id: "AMA-00001",
    patient_name: "Belle Beverly Olson",
    age_gender: "36, Male",
    validated: false,
    authorized: false,
  },
  {
    release_date: "21-Feb-2024, 11:20 PM",
    sample_number: "202403000045-02R",
    test_name: "Full Blood Picture",
    result_number: "RES-002",
    process_method: "Manual",
    source: "AMA",
    patient_id: "AMA-00001",
    patient_name: "Belle Beverly Olson",
    age_gender: "36, Male",
    validated: true,
    authorized: true,
  },
];

export const qc_data = [
  {
    id: 1,
    date: "21-Feb-2024, 11:20 PM",
    test_name: "3Part FPB",
    qc_number: "DH2307N",
    source_machine: "KT6300",
    added_controls: "3 Controls",
    done_by: "Super User",
    approval: "Pending",
    approved_by: "",
    notes: "no notes",
    controls: [
      {
        specimen: "Whole Blood",
        reference: "T051-6Months",
        spec_number: "DH2307N-01D",
        date: "21-FEB-2024, 11:20 PM",
        remarks: "no remarks",
        obs_results: qc_kt6610.observation_results,
      },
    ],
  },
  {
    id: 2,
    date: "22-Feb-2024, 11:20 PM",
    test_name: "5Part FBP",
    qc_number: "DH4118S",
    source_machine: "KT6610",
    added_controls: "3 Controls",
    done_by: "Super User",
    approval: "Pending",
    approved_by: "Super User",
    notes: "no notes",
    controls: [
      {
        specimen: "Whole Blood",
        reference: "T051-6Months",
        spec_number: "DH2307N-01D",
        date: "21-MAR-2024, 11:20 PM",
        remarks: "no remarks",
        obs_results: qc_kt6610.observation_results,
      },
      {
        specimen: "Whole Blood",
        reference: "T053-5Months",
        spec_number: "DH2508N-22D",
        date: "21-MAR-2024, 11:20 PM",
        remarks: "no remarks",
        obs_results: kt6300.observation_results,
      },
    ],
  },
  {
    id: 3,
    date: "23-Mar-2024, 11:20 PM",
    test_name: "Crea",
    qc_number: "DH3713G",
    source_machine: "GS100",
    added_controls: "3 Controls",
    done_by: "Super User",
    designation: "Clinician",
    approval: "Approved",
    approved_by: "Super User",
    notes: "no notes",
    controls: [
      {
        specimen: "Serum",
        reference: "T052-3Months",
        spec_number: "DH2308N-31D",
        date: "23-Mar-2024, 12:20 PM",
        remarks: "no remarks",
        obs_results: gs100.observation_results,
      },
    ],
  },
  {
    id: 4,
    date: "21-MAR-2024, 08:02 AM",
    test_name: "Alb",
    qc_number: "DH9987F",
    source_machine: "GS100",
    added_controls: "3 Controls",
    done_by: "Super User",
    approval: "Approved",
    approved_by: "Super User",
    notes: "no notes",
    controls: [
      {
        specimen: "Serum",
        reference: "T021-3Months",
        spec_number: "DH2418N-12D",
        date: "21-MAR-2024, 09:20 AM",
        remarks: "no remarks",
        obs_results: gs100.observation_results,
      },
    ],
  },
];

export const machines = [
  {
    id: 1,
    company: "Genrui",
    model: "KT6610",
  },
  {
    id: 2,
    company: "Genrui",
    model: "KT6300",
  },
  {
    id: 3,
    company: "Genrui",
    model: "GS100",
  },
  {
    id: 4,
    company: "Analyticon",
    model: "Urilyzer 100 Pro",
  },
];

export const qc_details: any = {
  date: "21-Feb-2024, 11:20 PM",
  done_by: "Super User",
  approval: "Pending",
  controls: [
    {
      specimen_number: "DH2307N-01D",
      location: "T051-6Months",
      specimen: "Whole Blood",
      expiry_date: "06-MAR-2025, 10:20 AM",
    },
  ],
};

export const ljPlotData: any = [
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 1),
    value: -1,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 1),
    value: -5,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 1),
    value: -1,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 2),
    value: -2,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 2),
    value: -3,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 3),
    value: -5,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 3),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 3),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 5),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 7),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 7),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 10),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 12),
    value: 4,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 13),
    value: 5,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 14),
    value: 2.2,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 15),
    value: 0,
  },
  {
    group: "Dataset 1",
    date: new Date(2019, 0, 15),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 1),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 1),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 1),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 2),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 2),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 3),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 3),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 3),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 5),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 6),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 7),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 7),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 9),
    value: 0,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 12),
    value: 4.1,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 14),
    value: 2.2,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 15),
    value: 4.3,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 15),
    value: 1.2,
  },
  {
    group: "Dataset 2",
    date: new Date(2019, 0, 15),
    value: 3,
  },
];

export const controlData = [
  {
    id: 1,
    specimen: "Whole Blood",
    number: "T051-6Months",
  },
  {
    id: 2,
    specimen: "Whole Blood",
    number: "T051-6Months",
  },
  {
    id: 3,
    specimen: "Whole Blood",
    number: "T051-6Months",
  },
  {
    id: 4,
    specimen: "Whole Blood",
    number: "T051-6Months",
  },
];

export const patient_document: any = {
  id: "PR582220",
  patient_name: "Denizer Frank Peter",
  age: "24",
  gender: "Female",
  address: "Pangani, Kibaha",
  sample_information: {
    sample_name: "Urine",
    section: "Chemistry L01",
    code: "CH0910",
    address: "Pangani, Kibaha",
    doctor: "Dr. Nia Bamgboshe",
    collection_date: "25-Mar-2024, 11:20 AM",
    received_date: "25-Mar-2024, 12:20 PM",
  },
  department: "Biochemistry Department",
  notes: "no notes",
  authorized: "Allan Joseph",
  author_title: "Technician",
  doctor: "Dr. Nia Bamgboshe",
  doctor_title: "MD, Haematology",
  test: "Full Blood Picture",
  order_number: "ORDER-00001D",
  results: kt6610.observation_results,
};

export const departments = [
  {
    id: 1,
    number: "H-1020",
    short_name: "HAEM",
    name: "Haematology Department",
    sections: "3 Sections",
    status: "Active",
    dept_head: "Dr. Masaka Masunga",
    date: "21-Mar-2024, 12:20 PM",
  },
  {
    id: 2,
    number: "H-2050",
    short_name: "BIOCHEM",
    name: "Biochemistry Department",
    sections: "2 Sections",
    status: "Active",
    dept_head: "Dr. Jonas Marwa",
    date: "21-Mar-2024, 12:20 PM",
  },
];
